[Main]
; app_mode - a link to configuration section (set "local" or "prod")
app_mode = prod

[local]
; This is configuration for local server
server_port = 5000
server_host = 127.0.0.1
debug_mode = True
workers = 1

[prod]
; This is configuration for prod server (in BTP Cloud Foundry deployment it will be overrided)
; Block the loading variables from .env file, because in BTP Cloud Foundry deployment environment variables provided in mta.yaml
server_port = 3000
server_host = 0.0.0.0
debug_mode = False
workers = 4